version: '3'

services:

  #MySQL用コンテナ
  mysql:

    container_name: mysql

    image: mysql:5.7

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    volumes:
      - ./mysql/var:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=root

      - MYSQL_DATABASE=test

      - MYSQL_USER=test

      - MYSQL_PASSWORD=test

      - TZ='Asia/Tokyo'

    ports:
      - 3306:3306


  #phpMyAdmin用コンテナ
  phpmyadmin:

    container_name: node_phpMyAdmin

    depends_on:
      - mysql

    image: phpmyadmin/phpmyadmin

    environment:

      PMA_HOST: node_mysql

    ports:
      - "80:80"

  #node用コンテナ
  node:
    image: node

    container_name: node

    tty: true

    environment:

      - NODE_ENV=development
    
    volumes:
      - ./src:/usr/src

    ports:
      - 3000:3000
    
    working_dir: /usr/src

    depends_on: ####
      - mysql
